// Generated by CoffeeScript 1.9.3
var Application, EventEmitter, Hooks, ScriptManager, app, err;

EventEmitter = require("events");

ScriptManager = require("./scriptmanager.js");

Hooks = new EventEmitter();

try {
  ScriptManager.LoadScripts("./scripts", Hooks);
} catch (_error) {
  err = _error;
  console.error("Error while loading user's scripts : " + err);
  console.error("Stack trace :");
  console.error(err.stack);
  process.exit(1);
}

Application = require("./app/application.js").Application;

app = new Application(Hooks);
