// Generated by CoffeeScript 1.9.3
var LoadScripts, fs;

fs = require("fs");

LoadScripts = function(path, hooks) {
  var files;
  files = fs.readdirSync(path);
  return files.every(function(file, index) {
    var err, extension, script;
    try {
      extension = file.split(".").pop();
    } catch (_error) {
      err = _error;
      console.error("Error while loading user script '" + file + "'' : " + err);
      console.error("Stack trace :");
      console.error(err.stack);
      process.exit(1);
    }
    if (extension === "js") {
      script = require(path + "/" + file);
      if (script) {
        try {
          script.initialize(hooks);
        } catch (_error) {
          err = _error;
          console.error("Error while initializing user script '" + file + "' : " + err);
          console.error("Stack trace :");
          console.error(err.stack);
          process.exit(1);
        }
      }
    }
    return true;
  });
};

exports.LoadScripts = LoadScripts;
