// Generated by CoffeeScript 1.9.3
var Command;

Command = (function() {
  function Command(app, mainscreen, name) {
    this.app = app;
    this.mainscreen = mainscreen;
    this.storage = mainscreen.storage;
    this.name = name;
  }

  Command.prototype.haveSuggestions = function(argidx) {
    return false;
  };

  Command.prototype.suggestions = function(arg, argidx, args) {
    return [];
  };

  Command.prototype.argumentName = function(argidx) {
    return "Argument " + argidx;
  };

  Command.prototype.execute = function(args) {
    throw new Error("Abstract function not implemented");
  };

  Command.prototype.getHelpText = function() {
    throw new Error("Abstract function not implemented");
  };

  return Command;

})();

exports.Command = Command;
