// Generated by CoffeeScript 1.9.3
var Blessed, mbox, screen;

Blessed = require("blessed");

screen = null;

mbox = null;

exports.init = function(scrn) {
  return screen = scrn;
};

exports.showMessage = function(msg) {
  if (mbox == null) {
    mbox = Blessed.message({
      left: "center",
      top: "center",
      width: "50%",
      height: "50%",
      bg: "green",
      fg: "black"
    });
    screen.append(mbox);
  }
  mbox.log(String(msg));
  return screen.render();
};

exports.showError = function(msg) {
  if (mbox == null) {
    mbox = Blessed.message({
      left: "center",
      top: "center",
      width: "50%",
      height: "50%",
      bg: "green",
      fg: "black"
    });
    screen.append(mbox);
  }
  mbox.error(String(msg));
  return screen.render();
};
