// Generated by CoffeeScript 1.9.3
var Blessed, ChannelList, Debug, Discord, GuildList, InputPanel, MainScreen, MessagePanel, Notifications, Storage, UserPanel;

Blessed = require('blessed');

Discord = require('discord.js');

Debug = require('./debug.js');

Storage = require('./storage.js').Storage;

GuildList = require('./panels/guild-list.js').GuildList;

ChannelList = require('./panels/channel-list.js').ChannelList;

UserPanel = require('./panels/user.js').UserPanel;

InputPanel = require('./panels/input.js').InputPanel;

MessagePanel = require('./panels/message.js').MessagePanel;

Notifications = require('./panels/notifications.js').Notifications;

MainScreen = (function() {
  function MainScreen(app) {
    var self;
    this.app = app;
    this.screen = app.screen;
    this.hooks = app.hooks;
    this.client = app.client;
    Debug.init(this.screen);
    this.storage = new Storage(app);
    this.storage.fill();
    this.storage.setupEvents();
    this.guild_list = new GuildList(app, this);
    this.channel_list = new ChannelList(app, this);
    this.user_panel = new UserPanel(app, this);
    this.input_panel = new InputPanel(app, this);
    this.message_panel = new MessagePanel(app, this);
    this.notifications = new Notifications(app, this);
    this.guild_list.setupUI();
    this.channel_list.setupUI();
    this.user_panel.setupUI();
    this.input_panel.setupUI();
    this.message_panel.setupUI();
    this.notifications.setupUI();
    this.guild_list.setupEvents();
    this.channel_list.setupEvents();
    this.user_panel.setupEvents();
    this.input_panel.setupEvents();
    this.message_panel.setupEvents();
    this.notifications.setupEvents();
    this.screen.append(this.guild_list.box);
    this.screen.append(this.channel_list.box);
    this.screen.append(this.user_panel.box);
    this.screen.append(this.message_panel.box);
    this.screen.append(this.input_panel.box);
    this.screen.append(this.notifications.box);
    this.screen.append(this.input_panel.suggestions_panel.box);
    this.screen.append(this.message_panel.popup.box);
    this.screen.render();
    self = this;
    this.client.setTimeout(function() {
      self.guild_list.repopulate(self.storage.guilds);
      self.channel_list.repopulate(self.storage.getCurrentChannels());
      self.user_panel.update();
      return self.screen.render();
    }, 100);
  }

  return MainScreen;

})();

exports.MainScreen = MainScreen;
