// Generated by CoffeeScript 1.9.3
var Blessed, Suggestions;

Blessed = require("blessed");

Suggestions = (function() {
  function Suggestions(app, mainscreen, width, height) {
    this.app = app;
    this.mainscreen = mainscreen;
    this.width = width;
    this.height = height;
    this.box = null;
    this.list = null;
    this.rawlist = [];
  }

  Suggestions.prototype.setupUI = function() {
    this.box = Blessed.box({
      width: this.width,
      height: this.height,
      align: "center",
      padding: {
        top: 1,
        left: 1,
        right: 1,
        bottom: 1
      },
      style: {
        fg: "green",
        bg: "blue"
      }
    });
    this.list = Blessed.list({
      parent: this.box,
      mouse: true,
      keys: false,
      tags: true,
      items: [],
      left: 0,
      top: 1,
      width: "100%-2",
      height: "100%-2",
      align: "center",
      style: {
        fg: "white",
        bg: "blue",
        selected: {
          fg: "blue",
          bg: "white"
        },
        item: {
          fg: "white",
          bg: "blue"
        }
      }
    });
    return this.box.hide();
  };

  Suggestions.prototype.setupEvents = function() {};

  Suggestions.prototype.update = function(txt, list, left) {
    this.box.setContent(txt);
    this.list.clearItems();
    this.list.setItems(list);
    this.rawlist = list;
    this.updatePosition(left);
    return this.app.screen.render();
  };

  Suggestions.prototype.updatePosition = function(left) {
    throw new Error("Abstract function not implemented");
  };

  Suggestions.prototype.show = function() {
    return this.box.show();
  };

  Suggestions.prototype.hide = function() {
    return this.box.hide();
  };

  Suggestions.prototype.up = function() {
    return this.list.up(1);
  };

  Suggestions.prototype.down = function() {
    return this.list.down(1);
  };

  Suggestions.prototype.getSelected = function() {
    return this.rawlist[this.list.selected];
  };

  Suggestions.prototype.visible = function() {
    return !this.box.hidden;
  };

  return Suggestions;

})();

exports.Suggestions = Suggestions;
