// Generated by CoffeeScript 1.9.3
var Blessed, ChannelList, GuildList, UserPanel;

Blessed = require("blessed");

GuildList = require("./guild-list.js").GuildList;

ChannelList = require("./channel-list.js").ChannelList;

UserPanel = (function() {
  function UserPanel(app, mainscreen) {
    this.app = app;
    this.mainscreen = mainscreen;
    this.storage = mainscreen.storage;
    this.user = app.client.user;
    this.box = null;
    this.dmchannel = null;
  }

  UserPanel.prototype.setupUI = function() {
    this.box = Blessed.box({
      top: 0,
      left: 0,
      width: GuildList.WIDTH + ChannelList.WIDTH,
      height: 7,
      padding: 1,
      tags: true,
      style: {
        fg: "white",
        bg: "grey"
      }
    });
    return this.dmchannel = Blessed.button({
      parent: this.box,
      clickable: true,
      keyable: false,
      top: 4,
      left: 1,
      width: "40%",
      height: 1,
      content: "Friends",
      align: "center",
      style: {
        fg: "black",
        bg: "white",
        hover: {
          fg: "black",
          bg: "green"
        },
        focus: {
          fg: "green",
          bg: "black"
        }
      }
    });
  };

  UserPanel.prototype.setupEvents = function() {
    var self;
    self = this;
    this.storage.on("current-guild-changed", function(s) {
      return self.update();
    });
    this.storage.on("current-channel-changed", function(s) {
      return self.update();
    });
    this.dmchannel.on("click", function() {
      return self.dmchannel.press();
    });
    return this.dmchannel.on("press", function() {
      return self.storage.selectGuild(null);
    });
  };

  UserPanel.prototype.update = function() {
    var channel, friend, guild;
    guild = this.storage.current_guild;
    channel = this.storage.current_channel;
    this.box.setContent('');
    this.box.setLine(0, "Logged in as {bold}{magenta-fg}" + this.user.username + "{/}");
    if (guild != null) {
      this.box.setLine(1, " on {bold}{cyan-fg}" + guild.name + "{/}");
      return this.box.setLine(2, " in \#{bold}" + channel.name + "{/}");
    } else {
      friend = this.storage.dmchannels_user[channel.id];
      if (friend != null) {
        return this.box.setLine(1, " speaking with {bold}{cyan-fg}" + friend.username + "{/}");
      } else {
        return this.box.setLine(1, " speaking with {bold}{cyan-fg}????{/}");
      }
    }
  };

  return UserPanel;

})();

exports.UserPanel = UserPanel;
